[project]
name = "naas-provisioner"
version = "0.1.0"
description = "An experimental operator provisioning K8S namespaces according to a list of applications provided by an URL"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "kubernetes>=35.0.0",
    "pydantic>=2.0.0",
    "requests>=2.32.0",
    "pyyaml>=6.0",
]

# Optional dependencies ( pip install .[dev] or uv sync --extra dev)
[project.optional-dependencies]
dev = [
    "pytest>=8.0.0",
]

[project.scripts]
naas-provisioner = "app.main:main"

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["app*"]
