---
apiVersion: v1
kind: Namespace
metadata:
  name: naas-provisioner
  labels:
    app.kubernetes.io/name: naas-provisioner
    app.kubernetes.io/component: namespace
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: naas-provisioner-sa
  namespace: naas-provisioner
  labels:
    app.kubernetes.io/name: naas-provisioner
    app.kubernetes.io/component: service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: naas-provisioner
  labels:
    app.kubernetes.io/name: naas-provisioner
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: naas-provisioner
  labels:
    app.kubernetes.io/name: naas-provisioner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: naas-provisioner
subjects:
  - kind: ServiceAccount
    name: naas-provisioner-sa
    namespace: naas-provisioner
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: naas-provisioner
  namespace: naas-provisioner
  labels:
    app.kubernetes.io/name: naas-provisioner
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: naas-provisioner
  strategy:
    # avoid paralel updates
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: naas-provisioner
    spec:
      serviceAccountName: naas-provisioner-sa
      containers:
        - name: naas-provisioner
          image: ghcr.io/mborne/naas-provisioner:main
          imagePullPolicy: IfNotPresent
          env:
            - name: NAAS_APPLICATIONS_URL
              value: https://raw.githubusercontent.com/mborne/naas-provisioner/refs/heads/main/docs/sample-applications.yaml
            - name: NAAS_ADMINS_CLUSTER_ROLE
              value: admin
            - name: NAAS_DRY_RUN
              value: "1"
            - name: NAAS_POLL_INTERVAL_SECONDS
              value: "30"




